title: Postdoctoral Research
author: Sanjeev Sharma
email: sms4003@med.cornell.edu
description: > # this means to ignore newlines until "baseurl:" Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.
This page provides a brief overwiew of my Ongoing postdoctoral research work

# social links
twitter_username: sanjeev_msharma # DO NOT include the @ character, or else the build will fail!
github_username:  88sanjeev # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
