title: Sanjeev Sharma, PhD
author: 
email: sms4003@med.cornell.edu
description: This blog provides an overwiew of my research career
# this means to ignore newlines until "baseurl:"


# social links
twitter_username: sanjeev_msharma # DO NOT include the @ character, or else the build will fail!
github_username:  88sanjeev # DO NOT include the @ character, or else the build will fail!
LinkedIn_username: sanjeevmsharma

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
