title: Postdoctoral Research
author: Sanjeev Sharma
email: sms4003@med.cornell.edu
description: This page provides a brief overwiew of my Ongoing postdoctoral research work
# this means to ignore newlines until "baseurl:"
This page provides a brief overwiew of my Ongoing postdoctoral research work

# social links
twitter_username: sanjeev_msharma # DO NOT include the @ character, or else the build will fail!
github_username:  88sanjeev # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
